# Generated by Django 5.1.3 on 2024-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listnote',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
