# Generated by Django 5.1.3 on 2024-11-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_listnote_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listnote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
