# Generated by Django 5.1.3 on 2024-11-11 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_delete_boardnote'),
        ('notes', '0003_alter_listnote_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listnote',
            name='public_note',
        ),
        migrations.AddField(
            model_name='listnote',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board'),
        ),
    ]
