# Generated by Django 5.1.3 on 2024-11-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_delete_boardnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
